on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    name: Greeting
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Yarn install
        run: yarn install

      - name: hello
        uses: ./

  action-env:
    runs-on: ubuntu-latest
    name: Get env values
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get env
        uses: ./.github/actions/github-env
        id: hello
      - name: Echo github ref
        run: echo '${{ steps.hello.outputs.ref }}'
