on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    name: Greeting
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Yarn install
        run: yarn install

      - name: hello
        uses: ./