on:
  push:

name: Install Linuxbrew

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Cache linuxbrew
        uses: actions/cache@v1
        env:
          cache-name: cache-linuxbrew
        with:
          path: /home/linuxbrew/.linuxbrew
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}

      - name: Install Linuxbrew
        run: |
          git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
          mkdir ~/.linuxbrew/bin
          ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin
          eval $(~/.linuxbrew/bin/brew shellenv)

          brew --version

          brew tap aws/tap
          brew install aws-sam-cli

          brew update
          brew upgrade

      - name: ls
        run: ls -l /home/